version: "3.7"

services:
  backend:
    build: ./
    restart: always
    command: bash entrypoint.sh
    volumes:
      - ./:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ../.env.prod
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13.1
    container_name: bl_ishko_postgres
    restart: always
    volumes:
      - bl_ishko_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env.prod
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - backend

  redis:
    image: redis:alpine

  celery:
    build: ./
    restart: always
    command: celery -A bl_ishko worker -l info
    env_file:
      - ../.env.prod
    depends_on:
      - backend
      - redis

volumes:
  bl_ishko_postgres_data: